// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDouHTVkJwpv9cVeNMGb_AXs4o4ppN5N1Q',
    appId: '1:169124451719:web:da4470a43f877074b96f22',
    messagingSenderId: '169124451719',
    projectId: 'qrabsen-89193',
    authDomain: 'qrabsen-89193.firebaseapp.com',
    storageBucket: 'qrabsen-89193.appspot.com',
    measurementId: 'G-J2CTW8MX41',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMNJqtX_Fzxcrkf5O7jhHp52fBusK16z0',
    appId: '1:169124451719:android:ee7d6397183997d9b96f22',
    messagingSenderId: '169124451719',
    projectId: 'qrabsen-89193',
    storageBucket: 'qrabsen-89193.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOKy6eWRmX9vVWQhXK9NpdzWy9XuqrKI4',
    appId: '1:169124451719:ios:7ad2baecbf73c93bb96f22',
    messagingSenderId: '169124451719',
    projectId: 'qrabsen-89193',
    storageBucket: 'qrabsen-89193.appspot.com',
    iosBundleId: 'com.example.vikoAbsensi',
  );
}
